import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const langConfig = {
  vi: { flag: '🇻🇳', name: 'Tiếng Việt' },
  en: { flag: '🇬🇧', name: 'English' },
  zh: { flag: '🇨🇳', name: '中文' },
  jp: { flag: '🇯🇵', name: '日本語' },
  kr: { flag: '🇰🇷', name: '한국어' },
  fr: { flag: '🇫🇷', name: 'Français' },
  ru: { flag: '🇷🇺', name: 'Русский' },
  th: { flag: '🇹🇭', name: 'ไทย' }
};

const translations = {
  vi: {
    brand_name: "NUÔI TÔI",
    hero_tag: "🔋 Cần nạp năng lượng để tồn tại",
    hero_title_1: "HÃY",
    hero_title_highlight: "NUÔI TÔI",
    hero_subtitle: "Tôi hứa sao kê đầy đủ! 💯",
    hero_quote: "Tôi nghèo, tôi đói, nhưng tôi uy tín. Mỗi bữa ăn bạn mời, tôi sẽ ghi nhớ đến tận bữa sau.",
    stat_balance: "💰 Số Dư Hiện Tại",
    stat_realtime: "Realtime",
    stat_goal: "🎯 Mục tiêu tháng này",
    stat_cheer: "Sắp đủ tiền đóng học lại rồi...",
    plan_title: "Tôi Sẽ Dùng Tiền Vào Đâu?",
    plan_1: "Cứu dỗi cái dạ dày",
    plan_1_desc: "Ưu tiên số 1, lấp đầy chiếc bụng đói.",
    plan_2: "Sữa Milo & Kẹo",
    plan_3: "Bim bim (Snack)",
    history_title: "Sao Kê Realtime",
    table_time: "Thời gian",
    table_user: "Người chuyển/Nhận",
    table_amount: "Số tiền",
    table_content: "Nội dung",
    donate_title: "CỔNG TIẾP TẾ LƯƠNG THỰC",
    donate_desc: "Mỗi đóng góp của bạn là một bát cơm (hoặc gói mì) cho tôi.",
    qr_note: "2.000đ cũng nhận ạ",
    acc_num_label: "Số Tài Khoản",
    scan_note: "Quét mã bằng app ngân hàng nào cũng được ạ.",
    car_promise: "Tôi hứa sẽ không mua ô tô bằng tiền donate. Vì... tôi chưa có bằng lái!",
    disclaimer_title: "LƯU Ý:",
    disclaimer_text: "Mọi nội dung trên web đều mang tính giải trí, không nhằm mục đích xúc phạm hay chỉ trích bất kỳ cá nhân/tổ chức nào.",
    footer_project: "Dự án Nuôi Tôi.",
    toast_copied: "Đã sao chép số tài khoản: ",
    just_now: "Vừa xong",
    today: "Hôm nay",
    yesterday: "Hôm qua",
    report_title: "Báo cáo chi tiêu",
    withdrew: "Vừa rút quỹ",
    donated: "Vừa donate",
    pop_new: "Thông báo mới"
  },
  en: {
    brand_name: "FEED ME",
    hero_tag: "🔋 Need energy to survive",
    hero_title_1: "PLEASE",
    hero_title_highlight: "FEED ME",
    hero_subtitle: "Full transparency promised! 💯",
    hero_quote: "I'm poor, I'm hungry, but I'm legit. Every meal you sponsor, I'll remember until my next meal.",
    stat_balance: "💰 Current Balance",
    stat_realtime: "Realtime",
    stat_goal: "🎯 Monthly Goal",
    stat_cheer: "Almost enough for tuition fees...",
    plan_title: "Where Does The Money Go?",
    plan_1: "Fill the hungry stomach",
    plan_1_desc: "Priority #1, fill the hungry stomach.",
    plan_2: "Milo & Sweets",
    plan_3: "Snacks & Chips",
    history_title: "Realtime History",
    table_time: "Time",
    table_user: "Sender/Receiver",
    table_amount: "Amount",
    table_content: "Content",
    donate_title: "FOOD SUPPLY PORTAL",
    donate_desc: "Every contribution is a bowl of rice (or noodles) for me.",
    qr_note: "Even 2.000đ is appreciated",
    acc_num_label: "Account Number",
    scan_note: "Scan with any banking app.",
    car_promise: "I promise not to buy a car with donations. Because... I don't have a driver's license yet!",
    disclaimer_title: "DISCLAIMER:",
    disclaimer_text: "All content on this website is for entertainment purposes only and is not intended to offend or criticize any individual/organization.",
    footer_project: "Feed Me Project.",
    toast_copied: "Copied account number: ",
    just_now: "Just now",
    today: "Today",
    yesterday: "Yesterday",
    report_title: "Expense Report",
    withdrew: "Just withdrew",
    donated: "Just donated",
    pop_new: "New Notification"
  },
  zh: {
    brand_name: "养我",
    hero_tag: "🔋 需要能量生存",
    hero_title_1: "请",
    hero_title_highlight: "养我",
    hero_subtitle: "承诺完全透明！ 💯",
    hero_quote: "我很穷，我很饿，但我很正经。你赞助的每一顿饭，我都会记得直到下一顿。",
    stat_balance: "💰 当前余额",
    stat_realtime: "实时",
    stat_goal: "🎯 本月目标",
    stat_cheer: "快够学费了...",
    plan_title: "钱花在哪里？",
    plan_1: "重修学费",
    plan_1_desc: "第一优先级，拯救我的学位。",
    plan_2: "美禄 & 糖果",
    plan_3: "零食 & 薯片",
    history_title: "实时记录",
    table_time: "时间",
    table_user: "发送/接收",
    table_amount: "金额",
    table_content: "内容",
    donate_title: "食品供应门户",
    donate_desc: "每一份贡献对我来说都是一碗饭（或面条）。",
    qr_note: "2,000越南盾也感激",
    acc_num_label: "账号",
    scan_note: "支持任何银行App扫描。",
    car_promise: "我保证不用捐款买车。因为……我还没驾照！",
    disclaimer_title: "注意：",
    disclaimer_text: "本网站所有内容仅供娱乐，无意冒犯或批评任何个人/组织。",
    footer_project: "养我计划。",
    toast_copied: "已复制账号： ",
    just_now: "刚刚",
    today: "今天",
    yesterday: "昨天",
    report_title: "支出报告",
    withdrew: "刚取出",
    donated: "刚捐赠",
    pop_new: "新通知"
  },
  jp: {
    brand_name: "私を養って",
    hero_tag: "🔋 生きるためにエネルギーが必要",
    hero_title_1: "お願い",
    hero_title_highlight: "私を養って",
    hero_subtitle: "完全な透明性を約束します！ 💯",
    hero_quote: "私は貧しく、お腹が空いていますが、正当です。スポンサーしてくれた食事は、次の食事まで覚えています。",
    stat_balance: "💰 現在の残高",
    stat_realtime: "リアルタイム",
    stat_goal: "🎯 今月の目標",
    stat_cheer: "授業料にはもうすぐ足りる...",
    plan_title: "お金はどこへ消える？",
    plan_1: "再履修の授業料",
    plan_1_desc: "優先順位1位、学位を救うため。",
    plan_2: "ミロとお菓子",
    plan_3: "スナックとポテチ",
    history_title: "リアルタイム履歴",
    table_time: "時間",
    table_user: "送金者/受取人",
    table_amount: "金額",
    table_content: "内容",
    donate_title: "食料供給ポータル",
    donate_desc: "すべての寄付は私にとって一杯のご飯（またはラーメン）です。",
    qr_note: "2,000ドンでも感謝します",
    acc_num_label: "口座番号",
    scan_note: "どの銀行アプリでもスキャン可能です。",
    car_promise: "寄付金で車を買わないと約束します。なぜなら…まだ免許を持っていないからです！",
    disclaimer_title: "免責事項:",
    disclaimer_text: "このウェブサイトのすべてのコンテンツは娯楽目的であり、個人や団体を不快にさせたり批判したりする意図はありません。",
    footer_project: "Feed Me Project.",
    toast_copied: "口座番号をコピーしました: ",
    just_now: "たった今",
    today: "今日",
    yesterday: "昨日",
    report_title: "支出報告",
    withdrew: "引き出した",
    donated: "寄付された",
    pop_new: "新しい通知"
  },
  kr: {
    brand_name: "나를 키워줘",
    hero_tag: "🔋 생존을 위해 에너지가 필요해",
    hero_title_1: "제발",
    hero_title_highlight: "나를 키워줘",
    hero_subtitle: "투명한 공개 약속! 💯",
    hero_quote: "가난하고 배고프지만, 저는 정직합니다. 후원해주신 밥 한 끼, 다음 식사 때까지 기억할게요.",
    stat_balance: "💰 현재 잔액",
    stat_realtime: "실시간",
    stat_goal: "🎯 이번 달 목표",
    stat_cheer: "재수강비가 거의 모였어요...",
    plan_title: "돈은 어디에 쓰나요?",
    plan_1: "재수강 등록금",
    plan_1_desc: "우선순위 1위, 학위를 구하자.",
    plan_2: "마일로 & 사탕",
    plan_3: "과자 & 간식",
    history_title: "실시간 내역",
    table_time: "시간",
    table_user: "보낸사람/받는사람",
    table_amount: "금액",
    table_content: "내용",
    donate_title: "식량 보급 포털",
    donate_desc: "모든 기부는 저에게 밥 한 공기(또는 라면)가 됩니다.",
    qr_note: "2,000동도 감사합니다",
    acc_num_label: "계좌 번호",
    scan_note: "모든 은행 앱으로 스캔 가능합니다.",
    car_promise: "기부금으로 차를 사지 않겠다고 약속합니다. 왜냐하면... 아직 운전면허가 없거든요!",
    disclaimer_title: "주의:",
    disclaimer_text: "본 웹사이트의 모든 콘텐츠는 오락용이며, 특정 개인/단체를 모욕하거나 비판할 의도가 없습니다.",
    footer_project: "Feed Me Project.",
    toast_copied: "계좌 번호 복사 완료: ",
    just_now: "방금",
    today: "오늘",
    yesterday: "어제",
    report_title: "지출 보고",
    withdrew: "출금 완료",
    donated: "기부 받음",
    pop_new: "새로운 알림"
  },
  fr: {
    brand_name: "NOURRIS-MOI",
    hero_tag: "🔋 Besoin d'énergie pour survivre",
    hero_title_1: "SVP",
    hero_title_highlight: "NOURRIS-MOI",
    hero_subtitle: "Transparence totale promise ! 💯",
    hero_quote: "Je suis pauvre, j'ai faim, mais je suis honnête. Chaque repas offert, je m'en souviendrai jusqu'au suivant.",
    stat_balance: "💰 Solde Actuel",
    stat_realtime: "En direct",
    stat_goal: "🎯 Objectif du mois",
    stat_cheer: "Presque assez pour les frais de scolarité...",
    plan_title: "Où va l'argent ?",
    plan_1: "Frais de rattrapage",
    plan_1_desc: "Priorité n°1, sauver mon diplôme.",
    plan_2: "Milo & Bonbons",
    plan_3: "Snacks & Chips",
    history_title: "Historique en direct",
    table_time: "Heure",
    table_user: "Expéditeur/Receveur",
    table_amount: "Montant",
    table_content: "Contenu",
    donate_title: "PORTAIL DE RAVITAILLEMENT",
    donate_desc: "Chaque contribution est un bol de riz (ou de nouilles) pour moi.",
    qr_note: "Même 2.000đ sont appréciés",
    acc_num_label: "Numéro de compte",
    scan_note: "Scannez avec n'importe quelle app bancaire.",
    car_promise: "Je promets de ne pas acheter de voiture avec les dons. Parce que... je n'ai pas encore mon permis !",
    disclaimer_title: "ATTENTION :",
    disclaimer_text: "Tout le contenu de ce site est à des fins de divertissement et n'a pas pour but d'offenser ou de critiquer un individu/une organisation.",
    footer_project: "Projet Feed Me.",
    toast_copied: "Compte copié : ",
    just_now: "À l'instant",
    today: "Aujourd'hui",
    yesterday: "Hier",
    report_title: "Rapport de dépenses",
    withdrew: "Vient de retirer",
    donated: "Vient de donner",
    pop_new: "Nouvelle notification"
  },
  ru: {
    brand_name: "ПОКОРМИ МЕНЯ",
    hero_tag: "🔋 Нужна энергия для жизни",
    hero_title_1: "ПОЖАЛУЙСТА",
    hero_title_highlight: "ПОКОРМИ",
    hero_subtitle: "Полная прозрачность! 💯",
    hero_quote: "Я беден, я голоден, но я честен. Каждый ваш обед я буду помнить до следующего.",
    stat_balance: "💰 Текущий баланс",
    stat_realtime: "В реальном времени",
    stat_goal: "🎯 Цель месяца",
    stat_cheer: "Почти хватает на пересдачу...",
    plan_title: "Куда уходят деньги?",
    plan_1: "Оплата пересдачи",
    plan_1_desc: "Приоритет №1, спасаю диплом.",
    plan_2: "Мило и сладости",
    plan_3: "Снэки и чипсы",
    history_title: "История (Live)",
    table_time: "Время",
    table_user: "Отправитель",
    table_amount: "Сумма",
    table_content: "Сообщение",
    donate_title: "ПОРТАЛ СНАБЖЕНИЯ",
    donate_desc: "Каждый вклад — это тарелка риса (или лапши) для меня.",
    qr_note: "Даже 2.000đ важны",
    acc_num_label: "Номер счета",
    scan_note: "Сканируйте любым банковским приложением.",
    car_promise: "Обещаю не покупать машину на донаты. Потому что... у меня еще нет прав!",
    disclaimer_title: "ВНИМАНИЕ:",
    disclaimer_text: "Весь контент на этом сайте предназначен только для развлекательных целей и не направлен на оскорбление или критику каких-либо лиц/организаций.",
    footer_project: "Проект Feed Me.",
    toast_copied: "Скопировано: ",
    just_now: "Только что",
    today: "Сегодня",
    yesterday: "Вчера",
    report_title: "Отчет о расходах",
    withdrew: "Только что снял",
    donated: "Только что задонатил",
    pop_new: "Новое уведомление"
  },
  th: {
    brand_name: "เลี้ยงฉันหน่อย",
    hero_tag: "🔋 ต้องการพลังงานเพื่อความอยู่รอด",
    hero_title_1: "ได้โปรด",
    hero_title_highlight: "เลี้ยงฉัน",
    hero_subtitle: "สัญญาว่าจะโปร่งใส 100%! 💯",
    hero_quote: "ฉันจน ฉันหิว แต่ฉันจริงใจ ทุกมื้อที่คุณเลี้ยง ฉันจะจำไปจนถึงมื้อหน้า",
    stat_balance: "💰 ยอดเงินปัจจุบัน",
    stat_realtime: "เรียลไทม์",
    stat_goal: "🎯 เป้าหมายเดือนนี้",
    stat_cheer: "ใกล้จะพอค่าเทอมแล้ว...",
    plan_title: "เงินเอาไปทำอะไร?",
    plan_1: "ค่าลงเรียนซ้ำ",
    plan_1_desc: "ลำดับที่ 1 ช่วยชีวิตใบปริญญา",
    plan_2: "ไมโล & ลูกอม",
    plan_3: "ขนม & มันฝรั่งทอด",
    history_title: "ประวัติเรียลไทม์",
    table_time: "เวลา",
    table_user: "ผู้ส่ง/ผู้รับ",
    table_amount: "จำนวนเงิน",
    table_content: "ข้อความ",
    donate_title: "ช่องทางส่งเสบียง",
    donate_desc: "ทุกการบริจาคคือข้าวหนึ่งจาน (หรือบะหมี่) สำหรับฉัน",
    qr_note: "2,000 ดองก็รับนะ ❤️",
    acc_num_label: "เลขที่บัญชี",
    scan_note: "สแกนได้ทุกแอปธนาคาร",
    car_promise: "ฉันสัญญาว่าจะไม่นำเงินบริจาคไปซื้อรถ เพราะ... ฉันยังไม่มีใบขับขี่!",
    disclaimer_title: "หมายเหตุ:",
    disclaimer_text: "เนื้อหาทั้งหมดบนเว็บไซต์นี้เพื่อความบันเทิงเท่านั้น ไม่ได้มีเจตนาล่วงเกินหรือวิจารณ์บุคคล/องค์กรใดๆ",
    footer_project: "โครงการเลี้ยงฉัน",
    toast_copied: "คัดลอกเลขบัญชีแล้ว: ",
    just_now: "เมื่อกี้",
    today: "วันนี้",
    yesterday: "เมื่อวาน",
    report_title: "รายงานการใช้จ่าย",
    withdrew: "เพิ่งถอนเงิน",
    donated: "เพิ่งโดเนท",
    pop_new: "การแจ้งเตือนใหม่"
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState('vi');

  const t = (key) => {
    return translations[currentLang][key] || key;
  };

  const changeLanguage = (lang) => {
    setCurrentLang(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  useEffect(() => {
    const savedLang = localStorage.getItem('preferredLanguage');
    if (savedLang && translations[savedLang]) {
      setCurrentLang(savedLang);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLang, changeLanguage, t, langConfig }}>
      {children}
    </LanguageContext.Provider>
  );
};

